name: cafeteriamaldonado_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^7.0.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.2.3
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  intl: ^0.19.0

  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
