// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36QjojgTWT-wg7ZFgWWT_IjBqERW23wU',
    appId: '1:893208786197:web:f19454ae8ac049ab28651c',
    messagingSenderId: '893208786197',
    projectId: 'app-cafeteria-maldonado',
    authDomain: 'app-cafeteria-maldonado.firebaseapp.com',
    storageBucket: 'app-cafeteria-maldonado.appspot.com',
    measurementId: 'G-DQY2VPEMKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnpj6vvMTpmVGEwoQH42Pof82h-W5Q9c0',
    appId: '1:893208786197:android:3f7eefab3d8de1f428651c',
    messagingSenderId: '893208786197',
    projectId: 'app-cafeteria-maldonado',
    storageBucket: 'app-cafeteria-maldonado.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw1xzA9jUxqbkvy2z6ifq2ht7N8waGib8',
    appId: '1:893208786197:ios:cfd3ba5ed6cd934228651c',
    messagingSenderId: '893208786197',
    projectId: 'app-cafeteria-maldonado',
    storageBucket: 'app-cafeteria-maldonado.appspot.com',
    iosBundleId: 'com.example.cafeteriamaldonadoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw1xzA9jUxqbkvy2z6ifq2ht7N8waGib8',
    appId: '1:893208786197:ios:cfd3ba5ed6cd934228651c',
    messagingSenderId: '893208786197',
    projectId: 'app-cafeteria-maldonado',
    storageBucket: 'app-cafeteria-maldonado.appspot.com',
    iosBundleId: 'com.example.cafeteriamaldonadoApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA36QjojgTWT-wg7ZFgWWT_IjBqERW23wU',
    appId: '1:893208786197:web:69ea5e5afadc6e4428651c',
    messagingSenderId: '893208786197',
    projectId: 'app-cafeteria-maldonado',
    authDomain: 'app-cafeteria-maldonado.firebaseapp.com',
    storageBucket: 'app-cafeteria-maldonado.appspot.com',
    measurementId: 'G-ETVH74NB3P',
  );
}
